### PR TITLE
added changes to fix AEM 65 issues

### PR DESCRIPTION
**Pull request by nikhilajudiya**
# type(scope): if this commit is applied, it will...
i.e. fix(login): [more detailed message]

# Why was this change made?

1. Implemented changes to support the AEM JSON model exporter. In SPA mode, the default `model.json` was not recognizing the schema app node and failed to include it via the default configuration.

2. Previously, our logic assumed that the schema app configuration would be added at the site root page. However, in the latest discussion with Vanguard, we learned that they expect the configuration to be added to any child page. To accommodate this, we enhanced the logic to query all pages where the schema app cloud configuration is applied. We also introduced scheduled jobs to update the configuration for all relevant child pages via APIs.

3. I have added additional logging throughout the code to better track the process flows and facilitate troubleshooting through logs.

# Links to any relevant tickets, articles, or other resources

closes #[16885](https://github.com/SchemaApp/SchemaApp/issues/16885)

# Other Notes

Did you fix any additional issues or do you have special notes for the reviewer? Put them here.

# Suggested Test for Reviewer

I have tested the changes locally, but the build keeps failing when I attempt to deploy the Angular SPA project to our cloud AEM server.

### CODE REVIEW

**Review by joelacummings — COMMENTED** [review]
@nikhilajudiya I need some detail on these changes. What are we changing, what issues did you find. Can you tie this to a bug or issue it should be closing. The PR template needs to be filled out so we know what is going out. 

Also regarding the version should it be 2.0.1? It looks to be jumping a few versions here.

**Comment by joelacummings** [comment]
@nikhilajudiya Sounds like there is some work left to get the build working, while you're doing that can you also fix the codacy issues, underscores in method names aren't up to Java standards, and one test isn't asserting anything. 
Screenshot 2024-10-14 at 9 52 55 PM

What are the next steps for fixing the build server?

**Comment by nikhilajudiya** [comment]
Getting below UI build error- 

17:33:24,085 [Exec Stream Pumper] [INFO] 18 10 2024 17:33:24.081:INFO [karma-server]: Karma v5.2.3 server started at http://localhost:9876/
17:33:24,086 [Exec Stream Pumper] [INFO] 18 10 2024 17:33:24.085:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
17:33:24,093 [Exec Stream Pumper] [INFO] (node:933) [log4js-node-DEP0004] DeprecationWarning: Pattern %d{DATE} is deprecated due to the confusion it causes when used. Please use %d{DATETIME} instead.
17:33:24,094 [Exec Stream Pumper] [INFO] (node:933) [log4js-node-DEP0004] DeprecationWarning: Pattern %d{DATE} is deprecated due to the confusion it causes when used. Please use %d{DATETIME} instead.
17:33:24,097 [Exec Stream Pumper] [INFO] 18 10 2024 17:33:24.096:INFO [launcher]: Starting browser ChromeHeadless
17:33:24,142 [Exec Stream Pumper] [INFO] (node:933) [log4js-node-DEP0004] DeprecationWarning: Pattern %d{DATE} is deprecated due to the confusion it causes when used. Please use %d{DATETIME} instead.
17:33:24,160 [Exec Stream Pumper] [INFO] 18 10 2024 17:33:24.160:ERROR [launcher]: Cannot start ChromeHeadless
17:33:24,161 [Exec Stream Pumper] [INFO] 	/build_root/build/schemaappdevenvtestsite/ui.frontend/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
17:33:24,161 [Exec Stream Pumper] [INFO] 
17:33:24,161 [Exec Stream Pumper] [INFO] 18 10 2024 17:33:24.160:ERROR [launcher]: ChromeHeadless stdout: 
17:33:24,161 [Exec Stream Pumper] [INFO] 18 10 2024 17:33:24.161:ERROR [launcher]: ChromeHeadless stderr: /build_root/build/schemaappdevenvtestsite/ui.frontend/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
17:33:24,161 [Exec Stream Pumper] [INFO] 
17:33:24,167 [Exec Stream Pumper] [INFO] (node:933) [log4js-node-DEP0004] DeprecationWarning: Pattern %d{DATE} is deprecated due to the confusion it causes when used. Please use %d{DATETIME} instead.
17:33:24,168 [Exec Stream Pumper] [INFO] (node:933) [log4js-node-DEP0004] DeprecationWarning: Pattern %d{DATE} is deprecated due to the confusion it causes when used. Please use %d{DATETIME} instead.
17:33:24,168 [Exec Stream Pumper] [INFO] (node:933) [log4js-node-DEP0004] DeprecationWarning: Pattern %d{DATE} is deprecated due to the confusion it causes when used. Please use %d{DATETIME} instead.
17:33:24,172 [Exec Stream Pumper] [INFO] 18 10 2024 17:33:24.171:INFO [launcher]: Trying to start ChromeHeadless again (1/2).
17:33:24,173 [Exec Stream Pumper] [INFO] (node:933) [log4js-node-DEP0004] DeprecationWarning: Pattern %d{DATE} is deprecated due to the confusion it causes when used. Please use %d{DATETIME} instead.
17:33:24,498 [Exec Stream Pumper] [INFO] 18 10 2024 17:33:24.498:ERROR [launcher]: Cannot start ChromeHeadless
17:33:24,498 [Exec Stream Pumper] [INFO] 	/build_root/build/schemaappdevenvtestsite/ui.frontend/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
17:33:24,498 [Exec Stream Pumper] [INFO] 
17:33:24,498 [Exec Stream Pumper] [INFO] 18 10 2024 17:33:24.498:ERROR [launcher]: ChromeHeadless stdout: 
17:33:24,498 [Exec Stream Pumper] [INFO] 18 10 2024 17:33:24.498:ERROR [launcher]: ChromeHeadless stderr: /build_root/build/schemaappdevenvtestsite/ui.frontend/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
17:33:24,499 [Exec Stream Pumper] [INFO] 
17:33:24,499 [Exec Stream Pumper] [INFO] (node:933) [log4js-node-DEP0004] DeprecationWarning: Pattern %d{DATE} is deprecated due to the confusion it causes when used. Please use %d{DATETIME} instead.
17:33:24,499 [Exec Stream Pumper] [INFO] (node:933) [log4js-node-DEP0004] DeprecationWarning: Pattern %d{DATE} is deprecated due to the confusion it causes when used. Please use %d{DATETIME} instead.
17:33:24,500 [Exec Stream Pumper] [INFO] (node:933) [log4js-node-DEP0004] DeprecationWarning: Pattern %d{DATE} is deprecated due to the confusion it causes when used. Please use %d{DATETIME} instead.
17:33:24,513 [Exec Stream Pumper] [INFO] 18 10 2024 17:33:24.513:INFO [launcher]: Trying to start ChromeHeadless again (2/2).
17:33:24,513 [Exec Stream Pumper] [INFO] 18 10 2024 17:33:24.513:INFO [launcher]: Trying to start ChromeHeadless again (2/2).(node:933) [log4js-node-DEP0004] DeprecationWarning: Pattern %d{DATE} is deprecated due to the confusion it causes when used. Please use %d{DATETIME} instead.
17:33:24,574 [Exec Stream Pumper] [INFO] 18 10 2024 17:33:24.574:ERROR [launcher]: Cannot start ChromeHeadless
17:33:24,574 [Exec Stream Pumper] [INFO] 	/build_root/build/schemaappdevenvtestsite/ui.frontend/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
17:33:24,574 [Exec Stream Pumper] [INFO] 
17:33:24,574 [Exec Stream Pumper] [INFO] 18 10 2024 17:33:24.574:ERROR [launcher]: ChromeHeadless stdout: 
17:33:24,574 [Exec Stream Pumper] [INFO] 18 10 2024 17:33:24.574:ERROR [launcher]: ChromeHeadless stderr: /build_root/build/schemaappdevenvtestsite/ui.frontend/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
17:33:24,574 [Exec Stream Pumper] [INFO] 
17:33:24,575 [Exec Stream Pumper] [INFO] (node:933) [log4js-node-DEP0004] DeprecationWarning: Pattern %d{DATE} is deprecated due to the confusion it causes when used. Please use %d{DATETIME} instead.
17:33:24,576 [Exec Stream Pumper] [INFO] (node:933) [log4js-node-DEP0004] DeprecationWarning: Pattern %d{DATE} is deprecated due to the confusion it causes when used. Please use %d{DATETIME} instead.
17:33:24,576 [Exec Stream Pumper] [INFO] (node:933) [log4js-node-DEP0004] DeprecationWarning: Pattern %d{DATE} is deprecated due to the confusion it causes when used. Please use %d{DATETIME} instead.
17:33:24,592 [Exec Stream Pumper] [INFO] 18 10 2024 17:33:24.592:ERROR [launcher]: ChromeHeadless failed 2 times (cannot start). Giving up.
17:33:24,596 [Exec Stream Pumper] [INFO] (node:933) [log4js-node-DEP0004] DeprecationWarning: Pattern %d{DATE} is deprecated due to the confusion it causes when used. Please use %d{DATETIME} instead.
17:33:24,639 [Exec Stream Pumper] [INFO] npm ERR! Test failed.  See above for more details.
17:33:24,648 [main] [INFO] ------------------------------------------------------------------------
17:33:24,648 [main] [INFO] Reactor Summary:
17:33:24,648 [main] [INFO] 
17:33:24,648 [main] [INFO] schemaappsite 1.0-SNAPSHOT ......................... SUCCESS [  1.468 s]
17:33:24,648 [main] [INFO] schemaappsite - Core 1.0-SNAPSHOT .................. SUCCESS [  9.480 s]
17:33:24,648 [main] [INFO] schemaappsite - UI Frontend 1.0-SNAPSHOT ........... FAILURE [01:30 min]
17:33:24,648 [main] [INFO] schemaappsite - Repository Structure Package 1.0-SNAPSHOT SKIPPED
17:33:24,648 [main] [INFO] schemaappsite - UI apps 1.0-SNAPSHOT ............... SKIPPED
17:33:24,649 [main] [INFO] schemaappsite - UI content 1.0-SNAPSHOT ............ SKIPPED
17:33:24,649 [main] [INFO] schemaappsite - UI config 1.0-SNAPSHOT ............. SKIPPED
17:33:24,649 [main] [INFO] schemaappsite - All 1.0-SNAPSHOT ................... SKIPPED
17:33:24,649 [main] [INFO] schemaappsite - Integration Tests 1.0-SNAPSHOT ..... SKIPPED
17:33:24,649 [main] [INFO] com.adobe.cq.cloud.testing.ui.cypress - UI Tests 0.0.1-SNAPSHOT SKIPPED
17:33:24,649 [main] [INFO] ------------------------------------------------------------------------
17:33:24,649 [main] [INFO] BUILD FAILURE
17:33:24,649 [main] [INFO] ------------------------------------------------------------------------
17:33:24,649 [main] [INFO] Total time:  01:44 min
17:33:24,650 [main] [INFO] Finished at: 2024-10-18T17:33:24Z
17:33:24,650 [main] [INFO] ------------------------------------------------------------------------
17:33:24,651 [main] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.0:npm (npm run test) on project schemaconnectorsite.ui.frontend: Failed to run task: 'npm test' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
17:33:24,651 [main] [ERROR] 
17:33:24,651 [main] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
17:33:24,652 [main] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
17:33:24,652 [main] [ERROR] 
17:33:24,652 [main] [ERROR] For more information about the errors and possible solutions, please read the following articles:
17:33:24,653 [main] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
17:33:24,653 [main] [ERROR] 
17:33:24,653 [main] [ERROR] After correcting the problems, you can resume the build with the command
17:33:24,654 [main] [ERROR]   mvn <args> -rf :schemaconnectorsite.ui.frontend

**Comment by joelacummings** [comment]
@nikhilajudiya What steps can I take to test, can you get something on the AEM server so I can look at it. Even model.json files?

**Comment by nikhilajudiya** [comment]
@joelacummings refer this - https://publish-p62138-e1451076.adobeaemcloud.com/content/schemaappsite/us/en.html and https://publish-p62138-e1451076.adobeaemcloud.com/content/schemaappsite/us/en.model.json

**Review by joelacummings — APPROVED** [review]
This did update, it updated overnight.

**Pull request merged**
